In [1]:
import numpy as np

In [2]:
l = [1,2,3]

In [3]:
np.array(l)

array([1, 2, 3])

In [4]:
nl = [[1,2],[2,3],[3,4]]

In [5]:
np.array(nl)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [7]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [13]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(2,5)

array([[0.72051486, 0.92945268, 0.06173219, 0.05516315, 0.52334134],
       [0.99864133, 0.88797196, 0.72749503, 0.3500904 , 0.13317125]])

In [16]:
np.random.randn(3,4)

array([[-0.02706881, -0.97216804, -2.05843714,  0.68310591],
       [-0.07200228, -0.82584598,  0.61063298,  0.47645575],
       [-0.39219934,  0.88016159, -0.84853871,  0.24989988]])

In [17]:
np.random.randint(1,100,size=(2,4))

array([[75, 64, 45, 38],
       [54, 96, 20,  7]])

In [18]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [22]:
ranarr.reshape(2,5)

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2]])

In [23]:
ranarr.max()

39

In [24]:
ranarr.min()

2

In [25]:
ranarr.argmax()

7

In [26]:
ranarr.dtype

dtype('int32')